export const SITE = {
  activeClients:  "21K+",
  instruments:    "500+",
  minDeposit:     "$10",
  maxLeverage:    "1:500",
  platform:       "MetaTrader 4",
  phone:          "+44 7418 641736",
  phoneHref:      "tel:+447418641736",
  email:          "info@ollatrade.com",
  supportEmail:   "cst@ollatrade.com",
  companyName:    "Olla Trade Ltd.",
  regNumber:      "A000001849",
  address:        "Grace Complex, The Valley, AI 2640, Anguilla",
  accountTypes:   ["Standard", "Pro", "Elite"] as const,
  registerUrl:    "https://direct.ollatrade.com/auth/register",
  loginUrl:       "https://direct.ollatrade.com/auth/login",
  articlesUrl:    "https://ollatrade.com/articles/",
  trustpilotUrl:  "https://www.trustpilot.com/review/ollatrade.com",
} as const;
