import { affiliateFaqs } from '../../data/faqs';
import type { Metadata } from "next";
import Link from "next/link";
import PageHero from "../../components/ui/PageHero";
import CTASection from "../../components/CTASection";
import FAQSection from "../../components/ui/FAQSection";
import FeatureGrid from "../../components/ui/FeatureGrid";
import { IconDollar, IconBarChart, IconUsers, IconHeadset, IconTarget, IconBell, IconBook, IconGlobe, IconMonitor, IconNewspaper, IconActivity, IconSettings } from "../../components/ui/Icons";

export const metadata: Metadata = {
  title: "Partner / Affiliate Program",
  description: "Join the Olla Trade affiliate program. Earn commissions from eligible referred clients, track performance in real time, and access dedicated partner support.",
};

const whyPartner = [
  { Icon: IconDollar,   title: "Earn Commissions",       desc: "Receive commissions from trading activity of eligible clients you refer through your unique tracking link." },
  { Icon: IconBarChart, title: "Real-Time Dashboard",     desc: "Access your partner portal to track referrals, conversions, commissions earned, and performance metrics." },
  { Icon: IconNewspaper,title: "Marketing Materials",     desc: "Access a library of professionally designed banners, landing pages, and promotional materials." },
  { Icon: IconHeadset,  title: "Dedicated Support",       desc: "A dedicated Olla Trade partner manager is assigned to your account to help you optimise performance." },
  { Icon: IconTarget,   title: "Custom Tracking Links",   desc: "Generate unique tracking links for each campaign or channel. Monitor clicks, registrations, and deposits separately." },
  { Icon: IconBell,     title: "Fast Commission Processing",desc: "Commissions are calculated and processed transparently on a regular cycle. No hidden deductions." },
];

const models = [
  { name: "CPA", full: "Cost Per Acquisition", best: "High-volume traffic sources", desc: "Earn a fixed commission for every eligible client you refer who completes registration and makes their first qualifying deposit.", points: ["Fixed fee per qualified referral","Paid after client's first deposit","Clear eligibility criteria"] },
  { name: "RevShare", full: "Revenue Share", best: "Long-term partnerships", desc: "Earn an ongoing percentage based on trading activity generated by clients you refer. Income can continue as long as referred clients are active.", points: ["Ongoing commission from active traders","Percentage of eligible spreads","Best for quality client referrals"], featured: true },
  { name: "Hybrid", full: "CPA + Revenue Share", best: "Established affiliates", desc: "Combine both CPA and revenue share. Get an upfront payment on qualified referrals plus ongoing revenue share.", points: ["CPA + revenue share combined","Available to high-performing partners","Custom terms by negotiation"] },
];

const benefits = [
  { Icon: IconMonitor,   title: "Display Banners",       desc: "IAB-standard banners in 10+ sizes including leaderboard, rectangle, skyscraper, and mobile formats." },
  { Icon: IconGlobe,     title: "Landing Pages",         desc: "Pre-built, conversion-optimised landing pages directly linked to your tracking ID." },
  { Icon: IconNewspaper, title: "Email Templates",       desc: "HTML email templates for promotional campaigns, deposits bonuses, and event-based messages." },
  { Icon: IconActivity,  title: "Social Media Creatives",desc: "Ready-to-use graphics for Facebook, Instagram, LinkedIn, and other platforms." },
  { Icon: IconBook,      title: "Brand Assets",          desc: "Official Olla Trade logo files, colour codes, typography guidelines, and usage documentation." },
  { Icon: IconSettings,  title: "Approved Copy",         desc: "Pre-approved advertising copy compliant with Olla Trade standards and industry guidelines." },
];

const steps = [
  { n: "01", t: "Apply Online",          d: "Complete the affiliate application form with your details, traffic source, and target market information." },
  { n: "02", t: "Application Review",   d: "Our affiliate team reviews your application within 2-3 business days and contacts you with next steps." },
  { n: "03", t: "Receive Tracking Link",d: "Once approved, you receive a unique affiliate tracking link and access to the partner portal and marketing materials." },
  { n: "04", t: "Promote Olla Trade",   d: "Use your tracking link, banners, and landing pages across your website, social media, email, or paid advertising." },
  { n: "05", t: "Track Performance",    d: "Monitor clicks, registrations, first deposits, and active traders in real time through your affiliate dashboard." },
  { n: "06", t: "Earn Commissions",     d: "Commissions from eligible referred clients are calculated transparently and processed on a regular payment cycle." },
];

const faqs = [
  { q: "Who can join the Olla Trade affiliate program?", a: "The program is open to individuals, companies, and digital marketing professionals who can send quality traffic. You must be able to refer clients eligible to open an Olla Trade account (not from restricted countries)." },
  { q: "Is there a cost to join?", a: "No. Joining the Olla Trade affiliate program is completely free. There are no setup fees or monthly charges." },
  { q: "How are commissions calculated?", a: "Commission calculations depend on the model agreed (CPA, Revenue Share, or Hybrid). Specific rates are confirmed during the affiliate approval process and documented in your affiliate agreement." },
  { q: "Are there restrictions on how I can promote Olla Trade?", a: "Yes. All promotions must comply with Olla Trade marketing guidelines and applicable advertising regulations. You may not make false claims, guarantee profits, or use deceptive practices." },
  { q: "Can I target clients in any country?", a: "No. You may not target residents of restricted countries (USA, Russia, Myanmar, UAE, Canada, Israel, New Zealand, Iran, North Korea). Targeting restricted jurisdictions may result in affiliate account termination." },
];

export default function AffiliatePage() {
  return (
    <>
      <PageHero badge="Affiliate & Partner Program" title="Earn Commissions by Partnering with Olla Trade" subtitle="Join our affiliate program and earn commissions from eligible clients you refer. Access real-time tracking, dedicated support, and professional marketing materials." breadcrumbs={[{ label: "Company", href: "/company" }, { label: "Partner / Affiliate" }]} cta={{ label: "Apply to Become a Partner", href: "https://direct.ollatrade.com/auth/register" }} stats={[{ value: "3", label: "Commission Models" }, { value: "Real-Time", label: "Tracking" }, { value: "24/5", label: "Partner Support" }]} />

      {/* Why partner */}
      <section className="py-16 bg-[#F5F7FA]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-[#111827] mb-3 text-center">Why Partner with Olla Trade?</h2>
          <p className="text-gray-500 text-center mb-10 max-w-xl mx-auto text-[15px]">We built our affiliate program to be transparent, fair, and genuinely rewarding for partners who send quality traffic.</p>
          <FeatureGrid features={whyPartner} cols={3} />
        </div>
      </section>

      {/* Commission models */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-[#111827] mb-3 text-center">Commission Models</h2>
          <p className="text-gray-500 text-center mb-10 max-w-xl mx-auto text-[15px]">Select the commission structure that best fits your traffic source. Specific rates are agreed during onboarding.</p>
          <div className="grid md:grid-cols-3 gap-5 mb-6">
            {models.map((m) => (
              <div key={m.name} className={`rounded-2xl border-2 flex flex-col p-7 ${m.featured ? "bg-[#050C15] border-[#00CC44]/25 shadow-xl" : "bg-[#F5F7FA] border-gray-100"}`}>
                {m.featured && <div className="text-[10px] font-bold text-[#00CC44]/60 uppercase tracking-widest mb-2">Recommended</div>}
                <div className={`text-2xl font-extrabold mb-1 ${m.featured ? "text-white" : "text-[#111827]"}`}>{m.name}</div>
                <div className={`text-[11px] mb-1 ${m.featured ? "text-[#00CC44]/60" : "text-[#1E88E5]"}`}>{m.full}</div>
                <div className={`text-[11px] mb-4 ${m.featured ? "text-white/25" : "text-gray-400"}`}>Best for: {m.best}</div>
                <p className={`text-[13px] leading-relaxed mb-5 flex-1 ${m.featured ? "text-white/45" : "text-gray-500"}`}>{m.desc}</p>
                <ul className="space-y-2 mb-5">
                  {m.points.map((p) => (
                    <li key={p} className={`text-[12px] flex items-center gap-2 ${m.featured ? "text-white/40" : "text-gray-500"}`}>
                      <div className="w-1.5 h-1.5 rounded-full bg-[#00CC44] flex-shrink-0" />{p}
                    </li>
                  ))}
                </ul>
                <Link href="mailto:info@ollatrade.com" className={`w-full flex items-center justify-center font-bold py-3 rounded-xl text-[13px] transition-colors ${m.featured ? "bg-[#00CC44] hover:bg-[#00DD4A] text-black" : "bg-[#111827] hover:bg-[#00CC44] text-white hover:text-black"}`}>
                  Enquire About {m.name}
                </Link>
              </div>
            ))}
          </div>
          <div className="border border-amber-200 bg-amber-50 rounded-xl p-4 text-[12px] text-amber-800 max-w-2xl mx-auto text-center">Olla Trade does not guarantee earnings. Commission amounts depend on eligible referred client activity. Specific rates are agreed during onboarding.</div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-16 bg-[#F5F7FA]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-[#111827] mb-10 text-center">How It Works</h2>
          <div className="space-y-4">
            {steps.map((s) => (
              <div key={s.n} className="flex items-start gap-5 bg-white rounded-2xl border border-gray-100 p-6">
                <div className="w-12 h-12 rounded-2xl bg-[#111827] text-[#00CC44] font-black text-[15px] flex items-center justify-center flex-shrink-0">{s.n}</div>
                <div>
                  <h3 className="text-[14px] font-bold text-[#111827] mb-1">{s.t}</h3>
                  <p className="text-[13px] text-gray-500 leading-relaxed">{s.d}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Marketing materials */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold text-[#111827] mb-3 text-center">Marketing Materials</h2>
          <p className="text-gray-500 text-center mb-10 max-w-xl mx-auto text-[15px]">A complete library of compliant, professional assets — pre-approved for immediate use.</p>
          <FeatureGrid features={benefits} cols={3} />
        </div>
      </section>

      <FAQSection title="Affiliate Program FAQs" faqs={affiliateFaqs} />
      <CTASection title="Start Earning with Olla Trade" subtitle="Apply to join our affiliate program and begin earning commissions from eligible referred clients." primaryLabel="Apply as a Partner" primaryHref="https://direct.ollatrade.com/auth/register" secondaryLabel="Contact Affiliate Team" secondaryHref="/company/contact" />

      {/* Compliance */}
      <section className="py-8 bg-white border-t border-gray-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-[#F5F7FA] border border-gray-200 rounded-xl p-5">
            <p className="text-[12px] text-gray-500 leading-relaxed">
              <strong className="text-gray-700">Affiliate Compliance Notice:</strong> Affiliates must not claim guaranteed earnings, guaranteed returns, or risk-free trading. All marketing must include appropriate risk warnings. Affiliates may not target restricted country residents. Contact: <a href="mailto:info@ollatrade.com" className="text-[#1E88E5] hover:underline">info@ollatrade.com</a>
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
